AllCops:
  Include:
    - "Gemfile"
    - "**/*.rb"
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "test/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "**/Rakefile"
    - "**/config.ru"
    - "node_modules/**/*"
    - "scripts/**/*"
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5
Style/FrozenStringLiteralComment:
  Enabled: false
Style/AndOr:
  EnforcedStyle: always
  Enabled: true
Style/CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW
Layout/DotPosition:
  EnforcedStyle: trailing
Style/For:
  EnforcedStyle: each
  SupportedStyles:
    - for
    - each
  Enabled: true
Layout/IndentationWidth:
  Width: 2
Style/NonNilCheck:
  IncludeSemanticChanges: true
Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
Layout/TrailingBlankLines:
  EnforcedStyle: final_newline
  SupportedStyles:
    - final_newline
    - final_blank_line
Metrics/LineLength:
  Max: 110
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 40
Metrics/AbcSize:
  Max: 25
  Exclude:
    - app/models/ability.rb
Metrics/PerceivedComplexity:
  Exclude:
    - app/models/ability.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/ability.rb
Style/Next:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: true
